### ISSUE TITLE
Post-link step fails when using ipywidgets from defaults

### ISSUE THREAD

**Issue by aburgm** [conda-forge/bqplot-feedstock#11] opened 2016-08-25 21:47 UTC
This is on win-64.

It works fine with ipywidgets from conda-forge.

```
Traceback (most recent call last):
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\Scripts\jupyter-nbextension-script.py", line 5, in <module>
    sys.exit(notebook.nbextensions.main())
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\traitlets\config\application.py", line 596, in launch_instance
    app.start()
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\notebook\nbextensions.py", line 961, in start
    super(NBExtensionApp, self).start()
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\jupyter_core\application.py", line 256, in start
    self.subapp.start()
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\notebook\nbextensions.py", line 869, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\notebook\nbextensions.py", line 845, in toggle_nbextension_python
    logger=self.log)
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\notebook\nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\notebook\nbextensions.py", line 374, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\notebook\nbextensions.py", line 1132, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\traitlets\utils\importstring.py", line 41, in import_item
    return __import__(parts[0])
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\bqplot\__init__.py", line 60, in <module>
    from .figure import *
  File "C:\Users\aburgmeier\AppData\Local\Miniconda3\envs\bla\lib\site-packages\bqplot\figure.py", line 31, in <module>
    from ipywidgets import DOMWidget, register, Color, widget_serialization
ImportError: No module named 'ipywidgets'
Error: Error: post-link failed for: conda-forge::bqplot-0.8.2-py35_0     |  85%
```

**Comment by aburgm** [comment] 2016-08-25 22:40
The defaults version has an additional dependency on _nb_ext_conf, which has a weird circular dependency with `nbpresent`. I wonder whether that leads to an incorrect link order in which ipywidgets is not yet present at the time bqplot gets linked. I also wonder whether that _nb_ext_conf thing being a dependency of ipywidgets isn't a mistake.

**Comment by SylvainCorlay** [comment] 2016-08-26 08:57
This is an issue in the default channel. `_nb_ext_conf` is meant to be part of the base anaconda distribution and not installed as a conda package.

**Comment by SylvainCorlay** [comment] 2016-08-26 08:59
cc - @damianavila @bollwyvl FYI

**Comment by damianavila** [comment] 2016-09-09 13:48
@aburgm I am trying to reproduce this issue unsuccessfully, can you give me more details about the process to get in that traceback? Thanks!

**Comment by aburgm** [comment] 2016-09-09 16:56
@damianavila I can still reprodure this. Here is my `condarc`:

```
channels:
    - defaults
    - conda-forge

show_channel_urls: True
channel_priority: False
```

Then I run `conda create -n bla2 bqplot` which produces this package plan:

```
    _nb_ext_conf:        0.3.0-py35_0       defaults
    anaconda-client:     1.5.1-py35_0       defaults
    bqplot:              0.8.2-py35_1       conda-forge
    clyent:              1.2.2-py35_0       defaults
    colorama:            0.3.7-py35_0       defaults
    decorator:           4.0.10-py35_0      defaults
    entrypoints:         0.2.2-py35_0       defaults
    ipykernel:           4.5.0-py35_0       defaults
    ipython:             5.1.0-py35_0       defaults
    ipython_genutils:    0.1.0-py35_0       defaults
    ipywidgets:          5.2.2-py35_0       defaults
    jinja2:              2.8-py35_1         defaults
    jsonschema:          2.5.1-py35_0       defaults
    jupyter_client:      4.4.0-py35_0       defaults
    jupyter_core:        4.1.1-py35_0       defaults
    markupsafe:          0.23-py35_2        defaults
    mistune:             0.7.3-py35_0       conda-forge
    mkl:                 11.3.3-1           defaults
    nb_anacondacloud:    1.2.0-py35_0       defaults
    nb_conda:            2.0.0-py35_0       defaults
    nb_conda_kernels:    2.0.0-py35_0       defaults
    nbconvert:           4.2.0-py35_0       defaults
    nbformat:            4.1.0-py35_0       defaults
    nbpresent:           3.0.2-py35_0       defaults
    notebook:            4.2.2-py35_0       defaults
    numpy:               1.11.1-py35_1      defaults
    pandas:              0.18.1-np111py35_0 defaults
    path.py:             8.2.1-py35_0       defaults
    pickleshare:         0.7.3-py35_0       defaults
    pip:                 8.1.2-py35_0       defaults
    prompt_toolkit:      1.0.7-py35_0       conda-forge
    pygments:            2.1.3-py35_0       defaults
    python:              3.5.2-0            defaults
    python-dateutil:     2.5.3-py35_0       defaults
    pytz:                2016.6.1-py35_0    defaults
    pyyaml:              3.11-py35_4        defaults
    pyzmq:               15.4.0-py35_0      defaults
    requests:            2.11.1-py35_0      defaults
    setuptools:          26.1.1-py35_0      defaults
    simplegeneric:       0.8.1-py35_1       defaults
    six:                 1.10.0-py35_0      defaults
    tornado:             4.4.1-py35_0       defaults
    traitlets:           4.3.0-py35_0       conda-forge
    vs2015_runtime:      14.0.25420-0       conda-forge
    wcwidth:             0.1.7-py35_0       defaults
    wheel:               0.29.0-py35_0      defaults
    widgetsnbextension:  1.2.6-py35_0       defaults
    win_unicode_console: 0.5-py35_0         defaults
```

Finally, it starts linking all the packages, and it's worthwhile to point out that it links `bqplot` before `ipywidgets`. When using ipywidgets from conda-forge, then it links it the other way around.

Hope this helps.

**Comment by damianavila** [comment] 2016-09-09 19:35
This is my output... in all the cases, it install fine...

```
$ cat .condarc
channels:
  - bokeh
  - defaults
  - conda-forge
(test_bqplot3) damian-S400CA :: ~ :: 
$ conda install bqplot
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/damian/miniconda3/envs/test_bqplot3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libsodium-1.0.10           |                0         1.2 MB
    decorator-4.0.10           |           py35_0          12 KB
    entrypoints-0.2.2          |           py35_0           6 KB
    ipython_genutils-0.1.0     |           py35_0          33 KB
    jsonschema-2.5.1           |           py35_0          56 KB
    ptyprocess-0.5.1           |           py35_0          19 KB
    pytz-2016.6.1              |           py35_0         177 KB
    pyzmq-15.4.0               |           py35_0         800 KB
    six-1.10.0                 |           py35_0          17 KB
    wcwidth-0.1.7              |           py35_0          21 KB
    jinja2-2.8                 |           py35_1         302 KB
    pickleshare-0.7.3          |           py35_0           8 KB
    python-dateutil-2.5.3      |           py35_0         237 KB
    terminado-0.6              |           py35_0          18 KB
    ipython-5.1.0              |           py35_0         991 KB
    jupyter_client-4.4.0       |           py35_0          99 KB
    nbformat-4.1.0             |           py35_0         117 KB
    ipykernel-4.5.0            |           py35_0         126 KB
    nbconvert-4.2.0            |           py35_0         315 KB
    notebook-4.2.2             |           py35_0         5.0 MB
    ipywidgets-5.2.2           |           py35_0          59 KB
    ------------------------------------------------------------
                                           Total:         9.6 MB

The following NEW packages will be INSTALLED:

    bqplot:             0.8.2-py35_1       conda-forge
    decorator:          4.0.10-py35_0                 
    entrypoints:        0.2.2-py35_0                  
    ipykernel:          4.5.0-py35_0                  
    ipython:            5.1.0-py35_0                  
    ipython_genutils:   0.1.0-py35_0                  
    ipywidgets:         5.2.2-py35_0                  
    jinja2:             2.8-py35_1                    
    jsonschema:         2.5.1-py35_0                  
    jupyter_client:     4.4.0-py35_0                  
    jupyter_core:       4.1.1-py35_0                  
    libsodium:          1.0.10-0                      
    markupsafe:         0.23-py35_2                   
    mistune:            0.7.2-py35_0                  
    mkl:                11.3.3-0                      
    nbconvert:          4.2.0-py35_0                  
    nbformat:           4.1.0-py35_0                  
    notebook:           4.2.2-py35_0                  
    numpy:              1.11.1-py35_0                 
    pandas:             0.18.1-np111py35_0            
    path.py:            8.2.1-py35_0                  
    pexpect:            4.0.1-py35_0                  
    pickleshare:        0.7.3-py35_0                  
    prompt_toolkit:     1.0.3-py35_0                  
    ptyprocess:         0.5.1-py35_0                  
    pygments:           2.1.3-py35_0                  
    python-dateutil:    2.5.3-py35_0                  
    pytz:               2016.6.1-py35_0               
    pyzmq:              15.4.0-py35_0                 
    simplegeneric:      0.8.1-py35_1                  
    six:                1.10.0-py35_0                 
    terminado:          0.6-py35_0                    
    tornado:            4.4.1-py35_0                  
    traitlets:          4.2.2-py35_0                  
    wcwidth:            0.1.7-py35_0                  
    widgetsnbextension: 1.2.6-py35_0                  
    zeromq:             4.1.4-0                       

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
libsodium-1.0. 100% |################################| Time: 0:00:02 442.06 kB/s
decorator-4.0. 100% |################################| Time: 0:00:00   4.76 MB/s
entrypoints-0. 100% |################################| Time: 0:00:00   1.58 MB/s
ipython_genuti 100% |################################| Time: 0:00:00  94.63 kB/s
jsonschema-2.5 100% |################################| Time: 0:00:00 149.37 kB/s
ptyprocess-0.5 100% |################################| Time: 0:00:00 108.23 kB/s
pytz-2016.6.1- 100% |################################| Time: 0:00:01 133.96 kB/s
pyzmq-15.4.0-p 100% |################################| Time: 0:00:02 319.98 kB/s
six-1.10.0-py3 100% |################################| Time: 0:00:00  74.39 kB/s
wcwidth-0.1.7- 100% |################################| Time: 0:00:00 116.74 kB/s
jinja2-2.8-py3 100% |################################| Time: 0:00:01 194.43 kB/s
pickleshare-0. 100% |################################| Time: 0:00:00   2.03 MB/s
python-dateuti 100% |################################| Time: 0:00:01 185.27 kB/s
terminado-0.6- 100% |################################| Time: 0:00:00 103.30 kB/s
ipython-5.1.0- 100% |################################| Time: 0:00:02 443.29 kB/s
jupyter_client 100% |################################| Time: 0:00:00 135.62 kB/s
nbformat-4.1.0 100% |################################| Time: 0:00:00 151.35 kB/s
ipykernel-4.5. 100% |################################| Time: 0:00:00 136.09 kB/s
nbconvert-4.2. 100% |################################| Time: 0:00:01 207.92 kB/s
notebook-4.2.2 100% |################################| Time: 0:00:05   1.02 MB/s
ipywidgets-5.2 100% |################################| Time: 0:00:00 110.72 kB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
Enabling notebook extension bqplot/extension...#########################  |  97%
      - Validating: OK
[      COMPLETE      ]|###################################################| 100%
(test_bqplot3) damian-S400CA :: ~ :: 
$ conda create -n test_bqplot4 bqplot
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/damian/miniconda3/envs/test_bqplot4:

The following NEW packages will be INSTALLED:

    bqplot:             0.8.2-py35_1       conda-forge
    decorator:          4.0.10-py35_0                 
    entrypoints:        0.2.2-py35_0                  
    ipykernel:          4.5.0-py35_0                  
    ipython:            5.1.0-py35_0                  
    ipython_genutils:   0.1.0-py35_0                  
    ipywidgets:         5.2.2-py35_0                  
    jinja2:             2.8-py35_1                    
    jsonschema:         2.5.1-py35_0                  
    jupyter_client:     4.4.0-py35_0                  
    jupyter_core:       4.1.1-py35_0                  
    libsodium:          1.0.10-0                      
    markupsafe:         0.23-py35_2                   
    mistune:            0.7.2-py35_0                  
    mkl:                11.3.3-0                      
    nbconvert:          4.2.0-py35_0                  
    nbformat:           4.1.0-py35_0                  
    notebook:           4.2.2-py35_0                  
    numpy:              1.11.1-py35_0                 
    openssl:            1.0.2h-1                      
    pandas:             0.18.1-np111py35_0            
    path.py:            8.2.1-py35_0                  
    pexpect:            4.0.1-py35_0                  
    pickleshare:        0.7.3-py35_0                  
    pip:                8.1.2-py35_0                  
    prompt_toolkit:     1.0.3-py35_0                  
    ptyprocess:         0.5.1-py35_0                  
    pygments:           2.1.3-py35_0                  
    python:             3.5.2-0                       
    python-dateutil:    2.5.3-py35_0                  
    pytz:               2016.6.1-py35_0               
    pyzmq:              15.4.0-py35_0                 
    readline:           6.2-2                         
    setuptools:         26.1.1-py35_0                 
    simplegeneric:      0.8.1-py35_1                  
    six:                1.10.0-py35_0                 
    sqlite:             3.13.0-0                      
    terminado:          0.6-py35_0                    
    tk:                 8.5.18-0                      
    tornado:            4.4.1-py35_0                  
    traitlets:          4.2.2-py35_0                  
    wcwidth:            0.1.7-py35_0                  
    wheel:              0.29.0-py35_0                 
    widgetsnbextension: 1.2.6-py35_0                  
    xz:                 5.2.2-0                       
    zeromq:             4.1.4-0                       
    zlib:               1.2.8-3                       

Proceed ([y]/n)? y

Linking packages ...
Enabling notebook extension bqplot/extension...#########################  |  97%
      - Validating: OK
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate test_bqplot4
#
# To deactivate this environment, use:
# $ source deactivate
#
```

Can you tell me your conda version?

Thanks!

**Comment by aburgm** [comment] 2016-09-09 21:37
My conda version is 4.1.12. Are you on Windows 64 bit?

**Comment by sandhujasmine** [comment] 2016-09-10 00:24
@aburgm @damianavila - I can reproduce this issue on a win-32 VM. However, I can get it to work if I install one at a time - don't know why.

Using the same .condarc as you have:

```
C:\Users\IEUser>more .condarc
channels:
    - defaults
    - conda-forge

show_channel_urls: True
channel_priority: False
```

Could you verify whether the following works for you:

```
conda create -n bqplot_ok ipywidgets
activate bqplot_ok
conda install bqplot
```

Here's my output:

```
C:\Users\IEUser>conda create -n bqplot_ok ipywidgets
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\IEUser\Miniconda3\envs\bqplot_ok:

The following NEW packages will be INSTALLED:

    _nb_ext_conf:        0.3.0-py35_0    defaults
    anaconda-client:     1.5.1-py35_0    defaults
    clyent:              1.2.2-py35_0    defaults
    colorama:            0.3.7-py35_0    defaults
    decorator:           4.0.10-py35_0   defaults
    entrypoints:         0.2.2-py35_0    defaults
    ipykernel:           4.5.0-py35_0    defaults
    ipython:             5.1.0-py35_0    defaults
    ipython_genutils:    0.1.0-py35_0    defaults
    ipywidgets:          5.2.2-py35_0    defaults
    jinja2:              2.8-py35_1      defaults
    jsonschema:          2.5.1-py35_0    defaults
    jupyter_client:      4.4.0-py35_0    defaults
    jupyter_core:        4.1.1-py35_0    defaults
    markupsafe:          0.23-py35_2     defaults
    mistune:             0.7.3-py35_0    conda-forge
    nb_anacondacloud:    1.2.0-py35_0    defaults
    nb_conda:            2.0.0-py35_0    defaults
    nb_conda_kernels:    2.0.0-py35_0    defaults
    nbconvert:           4.2.0-py35_0    defaults
    nbformat:            4.1.0-py35_0    defaults
    nbpresent:           3.0.2-py35_0    defaults
    notebook:            4.2.2-py35_0    defaults
    path.py:             8.2.1-py35_0    defaults
    pickleshare:         0.7.3-py35_0    defaults
    pip:                 8.1.2-py35_0    defaults
    prompt_toolkit:      1.0.7-py35_0    conda-forge
    pygments:            2.1.3-py35_0    defaults
    python:              3.5.2-0         defaults
    python-dateutil:     2.5.3-py35_0    defaults
    pytz:                2016.6.1-py35_0 defaults
    pyyaml:              3.11-py35_4     defaults
    pyzmq:               15.4.0-py35_0   defaults
    requests:            2.11.1-py35_0   defaults
    setuptools:          26.1.1-py35_0   defaults
    simplegeneric:       0.8.1-py35_1    defaults
    six:                 1.10.0-py35_0   defaults
    tornado:             4.4.1-py35_0    defaults
    traitlets:           4.3.0-py35_0    conda-forge
    vs2015_runtime:      14.0.25420-0    conda-forge
    wcwidth:             0.1.7-py35_0    defaults
    wheel:               0.29.0-py35_0   defaults
    widgetsnbextension:  1.2.6-py35_0    defaults
    win_unicode_console: 0.5-py35_0      defaults

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
No psutil available.
To proceed, please conda install psutil#
# To activate this environment, use:
# $ source activate bqplot_ok
#
# To deactivate this environment, use:
# $ source deactivate
#
C:\Users\IEUser>activate bqplot_ok

(bqplot_ok) C:\Users\IEUser>conda install bqplot
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\IEUser\Miniconda3\envs\bqplot_ok:

The following NEW packages will be INSTALLED:

    bqplot: 0.8.2-py35_1       conda-forge
    mkl:    11.3.3-1           defaults
    numpy:  1.11.1-py35_1      defaults
    pandas: 0.18.1-np111py35_0 defaults

Proceed ([y]/n)? y

Linking packages ...
Enabling notebook extension bqplot/extension...#############             |  75%
      - Validating: ok
[      COMPLETE      ]|##################################################| 100%

(bqplot_ok) C:\Users\IEUser>
```

**Comment by sandhujasmine** [comment] 2016-09-10 00:25
For completeness, here's the failure reproduced on win-32 VM using same .condarc:

```
C:\Users\IEUser>conda create -n bqplot_broken bqplot
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\IEUser\Miniconda3\envs\bqplot_broken:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vs2015_runtime-14.0.25420  |                0         1.8 MB  conda-forge
    colorama-0.3.7             |           py35_0          19 KB  defaults
    decorator-4.0.10           |           py35_0          12 KB  defaults
    entrypoints-0.2.2          |           py35_0           6 KB  defaults
    ipython_genutils-0.1.0     |           py35_0          34 KB  defaults
    jsonschema-2.5.1           |           py35_0          95 KB  defaults
    markupsafe-0.23            |           py35_2          27 KB  defaults
    mistune-0.7.3              |           py35_0          22 KB  conda-forge
    numpy-1.11.1               |           py35_1         2.6 MB  defaults
    path.py-8.2.1              |           py35_0          47 KB  defaults
    pygments-2.1.3             |           py35_0         1.3 MB  defaults
    pytz-2016.6.1              |           py35_0         171 KB  defaults
    pyyaml-3.11                |           py35_4         158 KB  defaults
    pyzmq-15.4.0               |           py35_0         451 KB  defaults
    requests-2.11.1            |           py35_0         665 KB  defaults
    setuptools-26.1.1          |           py35_0         755 KB  defaults
    simplegeneric-0.8.1        |           py35_1           7 KB  defaults
    six-1.10.0                 |           py35_0           8 KB  defaults
    tornado-4.4.1              |           py35_0         594 KB  defaults
    wcwidth-0.1.7              |           py35_0          21 KB  defaults
    win_unicode_console-0.5    |           py35_0          27 KB  defaults
    clyent-1.2.2               |           py35_0          15 KB  defaults
    jinja2-2.8                 |           py35_1         300 KB  defaults
    pickleshare-0.7.3          |           py35_0           8 KB  defaults
    pip-8.1.2                  |           py35_0         1.6 MB  defaults
    prompt_toolkit-1.0.7       |           py35_0         522 KB  conda-forge
    python-dateutil-2.5.3      |           py35_0         237 KB  defaults
    traitlets-4.3.0            |           py35_0         1.3 MB  conda-forge
    anaconda-client-1.5.1      |           py35_0         162 KB  defaults
    ipython-5.1.0              |           py35_0         1.0 MB  defaults
    jupyter_core-4.1.1         |           py35_0          96 KB  defaults
    pandas-0.18.1              |      np111py35_0         6.4 MB  defaults
    jupyter_client-4.4.0       |           py35_0         138 KB  defaults
    nbformat-4.1.0             |           py35_0         156 KB  defaults
    ipykernel-4.5.0            |           py35_0         126 KB  defaults
    nbconvert-4.2.0            |           py35_0         355 KB  defaults
    notebook-4.2.2             |           py35_0         5.1 MB  defaults
    widgetsnbextension-1.2.6   |           py35_0         1.1 MB  defaults
    bqplot-0.8.2               |           py35_1         884 KB  conda-forge
    ipywidgets-5.2.2           |           py35_0          59 KB  defaults
    nb_anacondacloud-1.2.0     |           py35_0          23 KB  defaults
    nb_conda_kernels-2.0.0     |           py35_0          30 KB  defaults
    nb_conda-2.0.0             |           py35_0          28 KB  defaults
    _nb_ext_conf-0.3.0         |           py35_0          924 B  defaults
    nbpresent-3.0.2            |           py35_0         485 KB  defaults
    ------------------------------------------------------------
                                           Total:        28.9 MB

The following NEW packages will be INSTALLED:

    _nb_ext_conf:        0.3.0-py35_0       defaults
    anaconda-client:     1.5.1-py35_0       defaults
    bqplot:              0.8.2-py35_1       conda-forge
    clyent:              1.2.2-py35_0       defaults
    colorama:            0.3.7-py35_0       defaults
    decorator:           4.0.10-py35_0      defaults
    entrypoints:         0.2.2-py35_0       defaults
    ipykernel:           4.5.0-py35_0       defaults
    ipython:             5.1.0-py35_0       defaults
    ipython_genutils:    0.1.0-py35_0       defaults
    ipywidgets:          5.2.2-py35_0       defaults
    jinja2:              2.8-py35_1         defaults
    jsonschema:          2.5.1-py35_0       defaults
    jupyter_client:      4.4.0-py35_0       defaults
    jupyter_core:        4.1.1-py35_0       defaults
    markupsafe:          0.23-py35_2        defaults
    mistune:             0.7.3-py35_0       conda-forge
    mkl:                 11.3.3-1           defaults
    nb_anacondacloud:    1.2.0-py35_0       defaults
    nb_conda:            2.0.0-py35_0       defaults
    nb_conda_kernels:    2.0.0-py35_0       defaults
    nbconvert:           4.2.0-py35_0       defaults
    nbformat:            4.1.0-py35_0       defaults
    nbpresent:           3.0.2-py35_0       defaults
    notebook:            4.2.2-py35_0       defaults
    numpy:               1.11.1-py35_1      defaults
    pandas:              0.18.1-np111py35_0 defaults
    path.py:             8.2.1-py35_0       defaults
    pickleshare:         0.7.3-py35_0       defaults
    pip:                 8.1.2-py35_0       defaults
    prompt_toolkit:      1.0.7-py35_0       conda-forge
    pygments:            2.1.3-py35_0       defaults
    python:              3.5.2-0            defaults
    python-dateutil:     2.5.3-py35_0       defaults
    pytz:                2016.6.1-py35_0    defaults
    pyyaml:              3.11-py35_4        defaults
    pyzmq:               15.4.0-py35_0      defaults
    requests:            2.11.1-py35_0      defaults
    setuptools:          26.1.1-py35_0      defaults
    simplegeneric:       0.8.1-py35_1       defaults
    six:                 1.10.0-py35_0      defaults
    tornado:             4.4.1-py35_0       defaults
    traitlets:           4.3.0-py35_0       conda-forge
    vs2015_runtime:      14.0.25420-0       conda-forge
    wcwidth:             0.1.7-py35_0       defaults
    wheel:               0.29.0-py35_0      defaults
    widgetsnbextension:  1.2.6-py35_0       defaults
    win_unicode_console: 0.5-py35_0         defaults

Proceed ([y]/n)? y

Fetching packages ...
vs2015_runtime 100% |###############################| Time: 0:00:01 949.28 kB/s
colorama-0.3.7 100% |###############################| Time: 0:00:00 178.91 kB/s
decorator-4.0. 100% |###############################| Time: 0:00:00   0.00  B/s
entrypoints-0. 100% |###############################| Time: 0:00:00   0.00  B/s
ipython_genuti 100% |###############################| Time: 0:00:00 172.83 kB/s
jsonschema-2.5 100% |###############################| Time: 0:00:00 309.89 kB/s
markupsafe-0.2 100% |###############################| Time: 0:00:00 224.27 kB/s
mistune-0.7.3- 100% |###############################| Time: 0:00:00 240.47 kB/s
numpy-1.11.1-p 100% |###############################| Time: 0:00:02   1.08 MB/s
path.py-8.2.1- 100% |###############################| Time: 0:00:00 180.81 kB/s
pygments-2.1.3 100% |###############################| Time: 0:00:03 349.45 kB/s
pytz-2016.6.1- 100% |###############################| Time: 0:00:00 486.79 kB/s
pyyaml-3.11-py 100% |###############################| Time: 0:00:00 296.00 kB/s
pyzmq-15.4.0-p 100% |###############################| Time: 0:00:01 374.27 kB/s
requests-2.11. 100% |###############################| Time: 0:00:01 444.52 kB/s
setuptools-26. 100% |###############################| Time: 0:00:01 475.56 kB/s
simplegeneric- 100% |###############################| Time: 0:00:00   0.00  B/s
six-1.10.0-py3 100% |###############################| Time: 0:00:00   0.00  B/s
tornado-4.4.1- 100% |###############################| Time: 0:00:01 533.45 kB/s
wcwidth-0.1.7- 100% |###############################| Time: 0:00:00 231.65 kB/s
win_unicode_co 100% |###############################| Time: 0:00:00 299.97 kB/s
clyent-1.2.2-p 100% |###############################| Time: 0:00:00 122.46 kB/s
jinja2-2.8-py3 100% |###############################| Time: 0:00:00 446.50 kB/s
pickleshare-0. 100% |###############################| Time: 0:00:00 553.02 kB/s
pip-8.1.2-py35 100% |###############################| Time: 0:00:02 739.08 kB/s
prompt_toolkit 100% |###############################| Time: 0:00:00 697.66 kB/s
python-dateuti 100% |###############################| Time: 0:00:00 486.25 kB/s
traitlets-4.3. 100% |###############################| Time: 0:00:01 819.31 kB/s
anaconda-clien 100% |###############################| Time: 0:00:00 320.10 kB/s
ipython-5.1.0- 100% |###############################| Time: 0:00:01 606.67 kB/s
jupyter_core-4 100% |###############################| Time: 0:00:00 216.41 kB/s
pandas-0.18.1- 100% |###############################| Time: 0:00:12 520.84 kB/s
jupyter_client 100% |###############################| Time: 0:00:00 322.64 kB/s
nbformat-4.1.0 100% |###############################| Time: 0:00:00 269.15 kB/s
ipykernel-4.5. 100% |###############################| Time: 0:00:00 330.61 kB/s
nbconvert-4.2. 100% |###############################| Time: 0:00:01 309.85 kB/s
notebook-4.2.2 100% |###############################| Time: 0:00:06 816.33 kB/s
widgetsnbexten 100% |###############################| Time: 0:00:07 147.74 kB/s
bqplot-0.8.2-p 100% |###############################| Time: 0:00:00   1.02 MB/s
ipywidgets-5.2 100% |###############################| Time: 0:00:00 204.87 kB/s
nb_anacondaclo 100% |###############################| Time: 0:00:00 250.97 kB/s
nb_conda_kerne 100% |###############################| Time: 0:00:00 282.47 kB/s
nb_conda-2.0.0 100% |###############################| Time: 0:00:00 205.80 kB/s
_nb_ext_conf-0 100% |###############################| Time: 0:00:00  59.14 kB/s
nbpresent-3.0. 100% |###############################| Time: 0:00:00 691.15 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
Traceback (most recent call last):###############################        |  85%
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\Scripts\jupyter-nbextension-script.py", line 5, in <module>
    sys.exit(notebook.nbextensions.main())
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\traitlets\config\application.py", line 653, in launch_instance
    app.start()
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\notebook\nbextensions.py", line 961, in start
    super(NBExtensionApp, self).start()
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\jupyter_core\application.py", line 256, in start
    self.subapp.start()
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\notebook\nbextensions.py", line 869, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\notebook\nbextensions.py", line 845, in toggle_nbextension_python
    logger=self.log)
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\notebook\nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\notebook\nbextensions.py", line 374, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\notebook\nbextensions.py", line 1132, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\traitlets\utils\importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\bqplot\__init__.py", line 60, in <module>
    from .figure import *
  File "C:\Users\IEUser\Miniconda3\envs\bqplot_broken\lib\site-packages\bqplot\figure.py", line 31, in <module>
    from ipywidgets import DOMWidget, register, Color, widget_serialization
ImportError: No module named 'ipywidgets'
Error: Error: post-link failed for: conda-forge::bqplot-0.8.2-py35_1

C:\Users\IEUser>
```

**Comment by damianavila** [comment] 2016-09-12 16:53
> My conda version is 4.1.12. Are you on Windows 64 bit?

This is why I asked @sandhujasmine to test on win as well here: https://github.com/ContinuumIO/anaconda-issues/issues/1051#issuecomment-246017176

And it seems to be tied to some platform dependent issue... because it seems to work OK on linux but not on win... @sandhujasmine I would suggest to discuss about this on the conda issue tracker as well, to see why this difference exist. My best guess... some conflict about how the channels are managed by conda, but it could be other things as well...

**Comment by SylvainCorlay** [comment] 2016-10-05 16:09
It seems that it is not a windows-only issue. I presume this is also the cause for the issue that we are seeing on binder with the server and notebook extensions

https://github.com/binder-project/binder/issues/80

This does not only impact bqplot but also **jupyterlab**, which is a serverextension, overriden by `_nb_ext_conf`.

**Comment by SylvainCorlay** [comment] 2016-10-05 16:26
^ @blink1073

**Comment by SylvainCorlay** [comment] 2016-10-05 17:04
@aburgm FYI I could get around this issue in the bqplot binder by disabling the default channel

(add the channel nodefaults to the environment)

**Comment by SylvainCorlay** [comment] 2018-02-16 12:53
Closing as post-link scripts will not be necessary for widget libraries after we require notebook > 5.4

**Closed as completed by SylvainCorlay** 2018-02-16 12:53 UTC
